version: '3.9'
services:
  database:
    container_name: database
    image: postgres:14.4-alpine3.16
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: swoogo
      POSTGRES_PASSWORD: swoogo
      POSTGRES_DB: integrations
    healthcheck:
      test: pg_isready -U swoogo -d integrations
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - db
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data

  #  localstack:
  #    container_name: 'localstack'
  #    image: localstack/localstack
  #    ports:
  #      - '4566:4566'            # LocalStack Gateway
  #      - '4510-4559:4510-4559'  # external services port range
  #    environment:
  #      DEBUG: 1
  #    networks:
  #      - db
  #    volumes:
  #      - './.volumes:/var/lib/localstack'
  #      - '/var/run/docker.sock:/var/run/docker.sock'
  #    links:
  #      - database
  #    depends_on:
  #      - database

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - db
    links:
      - database
    depends_on:
      - database

networks:
  db:
